<a href="https://colab.research.google.com/github/jumbokh/nknu-class/blob/main/notebooks/04_05__Sequential_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Sequential model

In [ ]:
import tensorflow as tf

## 建立模型結構

## 模型語法 1

In [ ]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation='softmax')
])

## 模型語法 2：將input_shape拿掉，以model參數設定

In [ ]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation='softmax')
])

x = tf.keras.layers.Input(shape=(28, 28))
# 或 x = tf.Variable(tf.random.truncated_normal([28, 28]))
y = model(x)

## 模型語法 3：可以直接串連神經層

In [ ]:
layer1 = tf.keras.layers.Dense(2, activation="relu", name="layer1")
layer2 = tf.keras.layers.Dense(3, activation="relu", name="layer2")
layer3 = tf.keras.layers.Dense(4, name="layer3")

# Call layers on a test input
x = tf.ones((3, 3))
y = layer3(layer2(layer1(x)))

## 臨時加減神經層

In [ ]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation='softmax')
])

# 刪減一層
model.pop()
print(f'神經層數: {len(model.layers)}')
model.layers

神經層數: 3


In [ ]:
# 增加一層
model.add(tf.keras.layers.Dense(10))
print(f'神經層數: {len(model.layers)}')
model.layers

神經層數: 4


## 取得模型及神經層資訊

In [ ]:
# 建立 3 layers
layer1 = tf.keras.layers.Dense(2, activation="relu", name="layer1", 
                               input_shape=(28, 28))
layer2 = tf.keras.layers.Dense(3, activation="relu", name="layer2")
layer3 = tf.keras.layers.Dense(4, name="layer3")

# 建立模型
model = tf.keras.models.Sequential([
  layer1,
  layer2,
  layer3
])

# 讀取模型權重
print(f'神經層參數類別總數: {len(model.weights)}')
model.weights

神經層參數類別總數: 6


[<tf.Variable 'layer1/kernel:0' shape=(28, 2) dtype=float32, numpy=
 array([[-0.40281397,  0.2205016 ],
        [-0.03376389,  0.15561956],
        [ 0.4151038 ,  0.02849016],
        [-0.15993604,  0.03800485],
        [ 0.06474555,  0.39933097],
        [ 0.41804487, -0.35671836],
        [-0.09304568, -0.12987521],
        [-0.07738718,  0.4214089 ],
        [-0.03624141, -0.15986142],
        [ 0.41953433, -0.14494684],
        [-0.16713199, -0.36726573],
        [ 0.28147936, -0.07306954],
        [ 0.06702495,  0.29314017],
        [-0.4076838 , -0.22369348],
        [ 0.35500747, -0.20532322],
        [-0.4465798 , -0.44517472],
        [-0.03784758,  0.18521959],
        [-0.32220033, -0.2665765 ],
        [-0.02831304, -0.01577556],
        [ 0.39644188, -0.16043621],
        [ 0.32985735,  0.40040267],
        [ 0.440423  , -0.3224007 ],
        [ 0.08332956, -0.33867747],
        [-0.14314255,  0.11406481],
        [-0.4151996 ,  0.03236541],
        [ 0.16692811,  0.4445855

In [ ]:
print(f'{layer2.name}: {layer2.weights}')

layer2: [<tf.Variable 'layer2/kernel:0' shape=(2, 3) dtype=float32, numpy=
array([[-0.85765153, -0.52234036,  0.6214608 ],
       [ 0.39134014,  0.85754156, -0.3411767 ]], dtype=float32)>, <tf.Variable 'layer2/bias:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>]


In [ ]:
# 取得模型彙總資訊
model.summary()

Model: "sequential_24"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
layer1 (Dense)               (None, 28, 2)             58        
_________________________________________________________________
layer2 (Dense)               (None, 28, 3)             9         
_________________________________________________________________
layer3 (Dense)               (None, 28, 4)             16        
_________________________________________________________________
layer4 (Dense)               (None, 28, 5)             25        
Total params: 108
Trainable params: 108
Non-trainable params: 0
_________________________________________________________________


## 一邊加神經層，一邊顯示模型彙總資訊，以利除錯

In [ ]:
from tensorflow.keras import layers

model = tf.keras.models.Sequential()
model.add(tf.keras.Input(shape=(250, 250, 3)))  # 250x250 RGB images
model.add(layers.Conv2D(32, 5, strides=2, activation="relu"))
model.add(layers.Conv2D(32, 3, activation="relu"))
model.add(layers.MaxPooling2D(3))

# 顯示目前模型彙總資訊
model.summary()

# The answer was: (40, 40, 32), so we can keep downsampling...

model.add(layers.Conv2D(32, 3, activation="relu"))
model.add(layers.Conv2D(32, 3, activation="relu"))
model.add(layers.MaxPooling2D(3))
model.add(layers.Conv2D(32, 3, activation="relu"))
model.add(layers.Conv2D(32, 3, activation="relu"))
model.add(layers.MaxPooling2D(2))

# 顯示目前模型彙總資訊
model.summary()

# Now that we have 4x4 feature maps, time to apply global max pooling.
model.add(layers.GlobalMaxPooling2D())

# Finally, we add a classification layer.
model.add(layers.Dense(10))

Model: "sequential_26"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 123, 123, 32)      2432      
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 121, 121, 32)      9248      
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 40, 40, 32)        0         
Total params: 11,680
Trainable params: 11,680
Non-trainable params: 0
_________________________________________________________________
Model: "sequential_26"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 123, 123, 32)      2432      
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 121, 121, 32)      9248      
__________________________

## 取得每一層神經層的output

In [ ]:
# 設定模型
initial_model = tf.keras.Sequential(
    [
        tf.keras.Input(shape=(250, 250, 3)),
        layers.Conv2D(32, 5, strides=2, activation="relu"),
        layers.Conv2D(32, 3, activation="relu"),
        layers.Conv2D(32, 3, activation="relu"),
    ]
)

# 設定模型的 input/output
feature_extractor = tf.keras.Model(
    inputs=initial_model.inputs,
    outputs=[layer.output for layer in initial_model.layers],
)

# 呼叫 feature_extractor 取得 output
x = tf.ones((1, 250, 250, 3))
features = feature_extractor(x)
features

[<tf.Tensor: shape=(1, 123, 123, 32), dtype=float32, numpy=
 array([[[[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          ...,
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],
 
         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          ...,
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],
 
         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          ...,
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],
 
         ...,
 
         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
         

In [ ]:
# 設定模型
initial_model = tf.keras.Sequential(
    [
        tf.keras.Input(shape=(250, 250, 3)),
        layers.Conv2D(32, 5, strides=2, activation="relu"),
        layers.Conv2D(32, 3, activation="relu", name="my_intermediate_layer"),
        layers.Conv2D(32, 3, activation="relu"),
    ]
)

# 設定模型的 input/output
feature_extractor = tf.keras.Model(
    inputs=initial_model.inputs,
    outputs=initial_model.get_layer(name="my_intermediate_layer").output,
)

# 呼叫 feature_extractor 取得 output
x = tf.ones((1, 250, 250, 3))
features = feature_extractor(x)
features

<tf.Tensor: shape=(1, 121, 121, 32), dtype=float32, numpy=
array([[[[0.        , 0.41995677, 0.32568812, ..., 0.27618825,
          0.        , 0.        ],
         [0.        , 0.41995677, 0.32568812, ..., 0.27618825,
          0.        , 0.        ],
         [0.        , 0.41995677, 0.32568812, ..., 0.27618825,
          0.        , 0.        ],
         ...,
         [0.        , 0.41995677, 0.32568812, ..., 0.27618825,
          0.        , 0.        ],
         [0.        , 0.41995677, 0.32568812, ..., 0.27618825,
          0.        , 0.        ],
         [0.        , 0.41995677, 0.32568812, ..., 0.27618825,
          0.        , 0.        ]],

        [[0.        , 0.41995677, 0.32568812, ..., 0.27618825,
          0.        , 0.        ],
         [0.        , 0.41995677, 0.32568812, ..., 0.27618825,
          0.        , 0.        ],
         [0.        , 0.41995677, 0.32568812, ..., 0.27618825,
          0.        , 0.        ],
         ...,
         [0.        , 0.41995