<a href="https://colab.research.google.com/github/jumbokh/nknu-class/blob/main/notebooks/%E6%88%91%E7%9A%84NumPy%E7%AD%86%E8%A8%98.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy簡介

> NumPy 是 <font color="Red">Num</font>erical <font color="Red">Py</font>thon 的簡稱，是 Python 用來作科學運算的基礎套件。

## 為什麼需要 NumPy?

> 簡單來說，因為原生的Python資料結構沒有支援向量運算！

> 而Numpy提供一個很容易做向量運算的新的資料結構ndarray (N-Dimensional Array)，以及可以處理ndarray資料的通用函式ufunc (Universal Functions)。 

In [ ]:
A = [1, 2, 3]
B = [4, 5, 6]

In [ ]:
A + B

[1, 2, 3, 4, 5, 6]

In [ ]:
A * 2

[1, 2, 3, 1, 2, 3]

In [ ]:
list(zip(A, B))

[(1, 4), (2, 5), (3, 6)]

In [ ]:
# 作法一

C = []

for i, j in zip(A, B):
  C.append(i+j)

C

[5, 7, 9]

In [ ]:
# 作法二
# list comprehension
C = [i+j for i,j in zip(A, B)]
C

[5, 7, 9]

In [ ]:
D = [i*2 for i in A]
D

[2, 4, 6]

## 載入numpy

```python
import numpy as np
```

In [ ]:
import numpy as np

In [ ]:
A1 = np.array(A)
B1 = np.array(B)

In [ ]:
A1 + B1

array([5, 7, 9])

In [ ]:
A1 * 2

array([2, 4, 6])

## ndarray簡介

ndarray有點像list，但是ndarray裡面的資料必須是同一個資料型態。另外，ndarray裡面還提供一些常用的屬性。

|屬性|說明|
|:--|:--|
|dtype|ndarray的資料型態|
|shape|ndarray形狀|
|ndim|ndarray的維度|
|size|ndarray的元素數量|

In [ ]:
A1

array([1, 2, 3])

In [ ]:
A1.dtype

dtype('int64')

In [ ]:
u = [1, 2, 3, 'abc', 5, 6]

In [ ]:
au = np.array(u)

In [ ]:
au

array(['1', '2', '3', 'abc', '5', '6'], dtype='<U21')

### 關於 tuple

In [ ]:
a = (1, 2)

In [ ]:
type(a)

tuple

In [ ]:
a = 1, 2

In [ ]:
type(a)

tuple

In [ ]:
a

(1, 2)

In [ ]:
a = (1)

In [ ]:
type(a)

int

In [ ]:
a = (1, )

In [ ]:
type(a)

tuple

In [ ]:
A1.shape

(3,)

In [ ]:
type(A1.shape)

tuple

In [ ]:
A1.ndim

1

In [ ]:
A1.size

3

## 如何創建 ndarray？

> 最簡單的方法就是使用 Numpy 的 array 函式。除此之外，還有底下的一些常用的創建方式。

|函式|說明|
|:-|:-|
|array|將輸入的資料轉換成 ndarray。|
|arange|range 的 ndarray 版。|
|linspace|返回平均分配特定區間的數值。|
|logspace|返回平均分配在 log scale 上的數值。|
|ones, ones_like|創建一個全部是1的ndarray。|
|zeros, zeros_like|創建一個全部是0的ndarray。|
|empty, empty_like|創建一個未初始化的ndarray。|
|eye, identity|創建一個單位矩陣。|

### 關於range

In [ ]:
for i in range(5):
  print(i)

0
1
2
3
4


In [ ]:
range?

In [ ]:
list(range(5))

[0, 1, 2, 3, 4]

In [ ]:
%%python2
import sys

a = range(100000)
print(sys.getsizeof(a))

800072


In [ ]:
%%python3
import sys

a = range(100000)
print(sys.getsizeof(a))

48


In [ ]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
list(range(5))

[0, 1, 2, 3, 4]

In [ ]:
list(range(5, 10))

[5, 6, 7, 8, 9]

In [ ]:
list(range(2, 10))

[2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
list(range(10, 3, -1))

[10, 9, 8, 7, 6, 5, 4]

### 練習:

請寫一個九九乘法表！

In [ ]:
for i in range(5):
  for j in range(5):
    print(i, j)

0 0
0 1
0 2
0 3
0 4
1 0
1 1
1 2
1 3
1 4
2 0
2 1
2 2
2 3
2 4
3 0
3 1
3 2
3 3
3 4
4 0
4 1
4 2
4 3
4 4


In [ ]:
for i in range(2, 10):
  for j in range(2, 10):
    print(i, "x", j, "=", i*j)

2 x 2 = 4
2 x 3 = 6
2 x 4 = 8
2 x 5 = 10
2 x 6 = 12
2 x 7 = 14
2 x 8 = 16
2 x 9 = 18
3 x 2 = 6
3 x 3 = 9
3 x 4 = 12
3 x 5 = 15
3 x 6 = 18
3 x 7 = 21
3 x 8 = 24
3 x 9 = 27
4 x 2 = 8
4 x 3 = 12
4 x 4 = 16
4 x 5 = 20
4 x 6 = 24
4 x 7 = 28
4 x 8 = 32
4 x 9 = 36
5 x 2 = 10
5 x 3 = 15
5 x 4 = 20
5 x 5 = 25
5 x 6 = 30
5 x 7 = 35
5 x 8 = 40
5 x 9 = 45
6 x 2 = 12
6 x 3 = 18
6 x 4 = 24
6 x 5 = 30
6 x 6 = 36
6 x 7 = 42
6 x 8 = 48
6 x 9 = 54
7 x 2 = 14
7 x 3 = 21
7 x 4 = 28
7 x 5 = 35
7 x 6 = 42
7 x 7 = 49
7 x 8 = 56
7 x 9 = 63
8 x 2 = 16
8 x 3 = 24
8 x 4 = 32
8 x 5 = 40
8 x 6 = 48
8 x 7 = 56
8 x 8 = 64
8 x 9 = 72
9 x 2 = 18
9 x 3 = 27
9 x 4 = 36
9 x 5 = 45
9 x 6 = 54
9 x 7 = 63
9 x 8 = 72
9 x 9 = 81


In [ ]:
list(range(5))*2

[0, 1, 2, 3, 4, 0, 1, 2, 3, 4]

In [ ]:
np.array(range(5))*2

array([0, 2, 4, 6, 8])

In [ ]:
np.arange(5)*2

array([0, 2, 4, 6, 8])

In [ ]:
np.arange(2, 10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.linspace(0, 100, 51)

array([  0.,   2.,   4.,   6.,   8.,  10.,  12.,  14.,  16.,  18.,  20.,
        22.,  24.,  26.,  28.,  30.,  32.,  34.,  36.,  38.,  40.,  42.,
        44.,  46.,  48.,  50.,  52.,  54.,  56.,  58.,  60.,  62.,  64.,
        66.,  68.,  70.,  72.,  74.,  76.,  78.,  80.,  82.,  84.,  86.,
        88.,  90.,  92.,  94.,  96.,  98., 100.])

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
f = np.ones((2, 3))

In [ ]:
f

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
f.shape

(2, 3)

In [ ]:
g = np.zeros(f.shape)

In [ ]:
g

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
h = np.zeros_like(f)

In [ ]:
h

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## ndarray的基本操作

### reshape

In [ ]:
G = np.arange(25)
G

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
G.shape

(25,)

In [ ]:
G.ndim

1

In [ ]:
G.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
G

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
H = G.reshape(5, 5)

In [ ]:
H

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
G.shape = 5, 5

In [ ]:
G

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### indexing & slicing

In [ ]:
A = [1, 2, 3]

In [ ]:
A[0]

1

In [ ]:
A[1]

2

In [ ]:
A1 = np.array(A)

In [ ]:
A1

array([1, 2, 3])

In [ ]:
A1[0]

1

In [ ]:
A1[1]

2

In [ ]:
G

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
G[1][1]

6

In [ ]:
G[1, 1]

6

In [ ]:
G[1:3][1:3]

array([[10, 11, 12, 13, 14]])

In [ ]:
G[1:3, 1:3]

array([[ 6,  7],
       [11, 12]])

In [ ]:
G

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
G[1]

array([5, 6, 7, 8, 9])

In [ ]:
G[1][1]

6

In [ ]:
G[1:3]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
G[1:3][1:3]

array([[10, 11, 12, 13, 14]])

In [ ]:
G

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
G[0]

array([0, 1, 2, 3, 4])

In [ ]:
G[0, :]

array([0, 1, 2, 3, 4])

In [ ]:
G[:, 0]

array([ 0,  5, 10, 15, 20])

In [ ]:
G[[1, 3],1]

array([ 6, 16])

### boolean indexing

In [ ]:
G

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
G > 10

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [ ]:
G[G>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
G[G>10] = 0

In [ ]:
G

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0]])

In [ ]:
G

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0]])

In [ ]:
K = np.arange(25)

In [ ]:
K[1][1]

IndexError: ignored

In [ ]:
type(K[1])

numpy.int64

In [ ]:
K.shape = 5, 5

In [ ]:
K

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
K[1:3][1:3]

array([[10, 11, 12, 13, 14]])

In [ ]:
type(K[1:3])

numpy.ndarray

In [ ]:
K[1:3].shape

(2, 5)

### 說明一下 indexing

In [ ]:
A = [1, 2, 3]

In [ ]:
A[1]

2

In [ ]:
A2 = 1

In [ ]:
type(A2)

int

In [ ]:
A2[1]

TypeError: ignored

In [ ]:
B1 = np.array([4, 5, 6])

In [ ]:
B1[1]

5

In [ ]:
B2 = B1[1]

In [ ]:
type(B2)

numpy.int64

In [ ]:
B2[0]

IndexError: ignored

## ufunc簡介

### 什麼是 ufunc？

* universal function 的縮寫
* 用來對 ndarray 裡面的每個元素作操作的函式。
* ufunc 可以被看作是一般 python 函式的向量化版本。
* Numpy 的 ufunc 都是衍生自 numpy.ufunc 類別。
* 很多內建的 ufunc 底層都是使用 C 實作的，所以速度很快。

詳細內容請參考：[ufuncs](https://docs.scipy.org/doc/numpy/reference/ufuncs.html)

In [ ]:
import math

In [ ]:
math.pi

3.141592653589793

In [ ]:
math.sin(math.pi/2)

1.0

In [ ]:
math.sin([1, 2, 3])

TypeError: ignored

In [ ]:
np.pi

3.141592653589793

In [ ]:
np.sin(np.pi/2)

1.0

In [ ]:
np.sin([1, 2, 3])

array([0.84147098, 0.90929743, 0.14112001])

### numpy 有哪些 ufuncs？

想知道 numpy 有哪些 ufunc ，可以參考官網上面的連結：[Available ufuncs](https://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs)

底下我們找一些常用的ufunc來用用看！

### 統計相關函式

參考：[Statistics](https://docs.scipy.org/doc/numpy-1.12.0/reference/routines.statistics.html)

|函式|說明|
|:-|:-|
|[sum](https://docs.scipy.org/doc/numpy/reference/generated/numpy.sum.html)|總和|
|[mean](https://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html)|平均|
|[std](https://docs.scipy.org/doc/numpy/reference/generated/numpy.std.html)|標準差|
|[var](https://docs.scipy.org/doc/numpy/reference/generated/numpy.var.html)|變異數|
|min, max|最小值、最大值|
|[argmin](https://docs.scipy.org/doc/numpy/reference/generated/numpy.argmin.html), [argmax](https://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html)|最小值的索引、最大值的索引|
|[cumsum](https://docs.scipy.org/doc/numpy/reference/generated/numpy.cumsum.html)|和的累計值|
|[cumprod](https://docs.scipy.org/doc/numpy/reference/generated/numpy.cumprod.html)|積的累計值|

### 亂數相關函式

參考：[Random Sampling (numpy.random)](https://docs.scipy.org/doc/numpy/reference/routines.random.html)

|函式|說明|
|:-|:-|
|[seed](https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.seed.html#numpy.random.seed)|設定亂數的種子|
|[permutation](https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.permutation.html)|隨機排列|
|[shuffle](https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.shuffle.html)|沿著 axis 0 的隨機排列|
|[rand](https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.rand.html#numpy.random.rand)|返回指定形狀的亂數，亂數值為[0,1]間的均勻分布|
|[randn](https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.randn.html#numpy.random.randn)|返回指定形狀的亂數，亂數值為mean為0，variance為1的高斯分布|
|[randint](https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.randint.html#numpy.random.randint)|使用離散均勻分布，返回指定形狀的整數亂數|
|[normal](https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.normal.html#numpy.random.normal)|返回指定形狀的亂數，亂數值為自訂的mean跟variance的高斯分布|
|[uniform](https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.uniform.html#numpy.random.uniform)|使用均勻分布，返回指定形狀的亂數|